### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sourvinos** [joaopgrassi/authz-custom-middleware#4]
I'm getting an "invalid uri" in the ServiceCollectionExtensions.cs
![Capture](https://user-images.githubusercontent.com/16444494/140721498-cbb755a7-2654-4b6d-a38b-f0d57d411b0f.jpg)

**Comment by joaopgrassi** [comment]
Hey @sourvinos. At which moment you get this? Can you describe it more? Hard to know from just looking at this. I didn't run this for a while since I published the post, but last time I tried all was working.

**Comment by joaopgrassi** [comment]
Closing this since no much activity in a while. Feel free to open/reach out if other things come up.
